Update nginx conf for better performance
MacareuxDigital/ansible-c5-ma pull request #11
Opened 2024-11-19 09:37 UTC by phoopw

- add cache for static files
- add text compression for js files
- fastcgi cache config update

2024-11-20 06:34 UTC, biplobice requested changes

2024-11-20 06:34 UTC, biplobice commented on prod-ansible-role/roles/nginx/templates/vhost_orig.conf.j2
> +        # Add 7 days expires to production
@phoopw It's 365 days, isn't it?

2024-11-20 06:34 UTC, biplobice commented on prod-ansible-role/roles/nginx/templates/vhost_orig_basicauth.conf.j2
> +        # Add 7 days expires to production
Same as above.

2024-11-21 04:33 UTC, phoopw commented on prod-ansible-role/roles/nginx/templates/vhost_orig_basicauth.conf.j2
> +        # Add 7 days expires to production
@biplobice I've changed the comment.

2024-11-21 05:51 UTC, biplobice approved these changes
@hissy LGTM.

2024-11-21 06:21 UTC, merged

2024-11-21 06:22 UTC, hissy commented
@phoopw @biplobice 

Thanks!